services:
    # Form types
    
    rk_helper_module.form.type.linkerquicknav:
        class: RK\HelperModule\Form\Type\QuickNavigation\LinkerQuickNavType
        arguments:
            - "@translator.default"
            - "@rk_helper_module.listentries_helper"
            - "@zikula_settings_module.locale_api"
            - "@rk_helper_module.feature_activation_helper"
        tags:
            - { name: form.type }
    
    rk_helper_module.form.type.carouselitemquicknav:
        class: RK\HelperModule\Form\Type\QuickNavigation\CarouselItemQuickNavType
        arguments:
            - "@translator.default"
            - "@request_stack"
            - "@rk_helper_module.listentries_helper"
            - "@zikula_settings_module.locale_api"
            - "@rk_helper_module.feature_activation_helper"
        tags:
            - { name: form.type }
    
    rk_helper_module.form.type.carouselquicknav:
        class: RK\HelperModule\Form\Type\QuickNavigation\CarouselQuickNavType
        arguments:
            - "@translator.default"
            - "@rk_helper_module.listentries_helper"
            - "@zikula_settings_module.locale_api"
            - "@rk_helper_module.feature_activation_helper"
        tags:
            - { name: form.type }
    
    rk_helper_module.form.type.imagequicknav:
        class: RK\HelperModule\Form\Type\QuickNavigation\ImageQuickNavType
        arguments:
            - "@translator.default"
            - "@rk_helper_module.listentries_helper"
            - "@rk_helper_module.feature_activation_helper"
        tags:
            - { name: form.type }
    
    rk_helper_module.form.type.infoquicknav:
        class: RK\HelperModule\Form\Type\QuickNavigation\InfoQuickNavType
        arguments:
            - "@translator.default"
            - "@rk_helper_module.listentries_helper"
            - "@zikula_settings_module.locale_api"
            - "@rk_helper_module.feature_activation_helper"
        tags:
            - { name: form.type }
    
    rk_helper_module.form.handler.linker:
        class: RK\HelperModule\Form\Handler\Linker\EditHandler
        arguments:
            - "@kernel"
            - "@translator.default"
            - "@form.factory"
            - "@request_stack"
            - "@router"
            - "@logger"
            - "@zikula_permissions_module.api.permission"
            - "@zikula_extensions_module.api.variable"
            - "@zikula_users_module.current_user"
            - "@rk_helper_module.entity_factory"
            - "@rk_helper_module.controller_helper"
            - "@rk_helper_module.model_helper"
            - "@rk_helper_module.selection_helper"
            - "@rk_helper_module.workflow_helper"
            - "@rk_helper_module.hook_helper"
            - "@rk_helper_module.translatable_helper"
            - "@rk_helper_module.feature_activation_helper"
        calls:
            - [setLockingApi, ["@?zikula_pagelock_module.api.locking"]]
        tags:
            - { name: form.type }
    
    rk_helper_module.form.type.linker:
        class: RK\HelperModule\Form\Type\LinkerType
        arguments:
            - "@translator.default"
            - "@rk_helper_module.entity_factory"
            - "@rk_helper_module.listentries_helper"
            - "@zikula_settings_module.locale_api"
            - "@rk_helper_module.feature_activation_helper"
        tags:
            - { name: form.type }
    
    rk_helper_module.form.handler.carouselitem:
        class: RK\HelperModule\Form\Handler\CarouselItem\EditHandler
        arguments:
            - "@kernel"
            - "@translator.default"
            - "@form.factory"
            - "@request_stack"
            - "@router"
            - "@logger"
            - "@zikula_permissions_module.api.permission"
            - "@zikula_extensions_module.api.variable"
            - "@zikula_users_module.current_user"
            - "@rk_helper_module.entity_factory"
            - "@rk_helper_module.controller_helper"
            - "@rk_helper_module.model_helper"
            - "@rk_helper_module.selection_helper"
            - "@rk_helper_module.workflow_helper"
            - "@rk_helper_module.hook_helper"
            - "@rk_helper_module.translatable_helper"
            - "@rk_helper_module.feature_activation_helper"
        calls:
            - [setLockingApi, ["@?zikula_pagelock_module.api.locking"]]
        tags:
            - { name: form.type }
    
    rk_helper_module.form.type.carouselitem:
        class: RK\HelperModule\Form\Type\CarouselItemType
        arguments:
            - "@translator.default"
            - "@rk_helper_module.entity_factory"
            - "@rk_helper_module.listentries_helper"
            - "@zikula_settings_module.locale_api"
            - "@rk_helper_module.feature_activation_helper"
        tags:
            - { name: form.type }
    
    rk_helper_module.form.handler.carousel:
        class: RK\HelperModule\Form\Handler\Carousel\EditHandler
        arguments:
            - "@kernel"
            - "@translator.default"
            - "@form.factory"
            - "@request_stack"
            - "@router"
            - "@logger"
            - "@zikula_permissions_module.api.permission"
            - "@zikula_extensions_module.api.variable"
            - "@zikula_users_module.current_user"
            - "@rk_helper_module.entity_factory"
            - "@rk_helper_module.controller_helper"
            - "@rk_helper_module.model_helper"
            - "@rk_helper_module.selection_helper"
            - "@rk_helper_module.workflow_helper"
            - "@rk_helper_module.hook_helper"
            - "@rk_helper_module.translatable_helper"
            - "@rk_helper_module.feature_activation_helper"
        calls:
            - [setLockingApi, ["@?zikula_pagelock_module.api.locking"]]
        tags:
            - { name: form.type }
    
    rk_helper_module.form.type.carousel:
        class: RK\HelperModule\Form\Type\CarouselType
        arguments:
            - "@translator.default"
            - "@rk_helper_module.entity_factory"
            - "@rk_helper_module.listentries_helper"
            - "@zikula_settings_module.locale_api"
            - "@rk_helper_module.feature_activation_helper"
        tags:
            - { name: form.type }
    
    rk_helper_module.form.handler.image:
        class: RK\HelperModule\Form\Handler\Image\EditHandler
        arguments:
            - "@kernel"
            - "@translator.default"
            - "@form.factory"
            - "@request_stack"
            - "@router"
            - "@logger"
            - "@zikula_permissions_module.api.permission"
            - "@zikula_extensions_module.api.variable"
            - "@zikula_users_module.current_user"
            - "@rk_helper_module.entity_factory"
            - "@rk_helper_module.controller_helper"
            - "@rk_helper_module.model_helper"
            - "@rk_helper_module.selection_helper"
            - "@rk_helper_module.workflow_helper"
            - "@rk_helper_module.hook_helper"
            - "@rk_helper_module.translatable_helper"
            - "@rk_helper_module.feature_activation_helper"
        calls:
            - [setLockingApi, ["@?zikula_pagelock_module.api.locking"]]
        tags:
            - { name: form.type }
    
    rk_helper_module.form.type.image:
        class: RK\HelperModule\Form\Type\ImageType
        arguments:
            - "@translator.default"
            - "@rk_helper_module.entity_factory"
            - "@rk_helper_module.listentries_helper"
            - "@rk_helper_module.feature_activation_helper"
        tags:
            - { name: form.type }
    
    rk_helper_module.form.handler.info:
        class: RK\HelperModule\Form\Handler\Info\EditHandler
        arguments:
            - "@kernel"
            - "@translator.default"
            - "@form.factory"
            - "@request_stack"
            - "@router"
            - "@logger"
            - "@zikula_permissions_module.api.permission"
            - "@zikula_extensions_module.api.variable"
            - "@zikula_users_module.current_user"
            - "@rk_helper_module.entity_factory"
            - "@rk_helper_module.controller_helper"
            - "@rk_helper_module.model_helper"
            - "@rk_helper_module.selection_helper"
            - "@rk_helper_module.workflow_helper"
            - "@rk_helper_module.hook_helper"
            - "@rk_helper_module.translatable_helper"
            - "@rk_helper_module.feature_activation_helper"
        calls:
            - [setLockingApi, ["@?zikula_pagelock_module.api.locking"]]
        tags:
            - { name: form.type }
    
    rk_helper_module.form.type.info:
        class: RK\HelperModule\Form\Type\InfoType
        arguments:
            - "@translator.default"
            - "@rk_helper_module.entity_factory"
            - "@zikula_extensions_module.api.variable"
            - "@rk_helper_module.translatable_helper"
            - "@rk_helper_module.listentries_helper"
            - "@zikula_settings_module.locale_api"
            - "@rk_helper_module.feature_activation_helper"
        tags:
            - { name: form.type }
    
    rk_helper_module.form.type.deleteentity:
        class: RK\HelperModule\Form\DeleteEntityType
        arguments:
            - "@translator.default"
        tags:
            - { name: form.type }
    
    rk_helper_module.form.type.block.itemlist:
        class: RK\HelperModule\Block\Form\Type\ItemListBlockType
        arguments:
            - "@translator.default"
        tags:
            - { name: form.type }
    
    rk_helper_module.form.type.linkerfinder:
        class: RK\HelperModule\Form\Type\Finder\LinkerFinderType
        arguments:
            - "@translator.default"
            - "@rk_helper_module.feature_activation_helper"
        tags:
            - { name: form.type }
    
    rk_helper_module.form.type.carouselitemfinder:
        class: RK\HelperModule\Form\Type\Finder\CarouselItemFinderType
        arguments:
            - "@translator.default"
            - "@rk_helper_module.feature_activation_helper"
        tags:
            - { name: form.type }
    
    rk_helper_module.form.type.carouselfinder:
        class: RK\HelperModule\Form\Type\Finder\CarouselFinderType
        arguments:
            - "@translator.default"
            - "@rk_helper_module.feature_activation_helper"
        tags:
            - { name: form.type }
    
    rk_helper_module.form.type.imagefinder:
        class: RK\HelperModule\Form\Type\Finder\ImageFinderType
        arguments:
            - "@translator.default"
            - "@rk_helper_module.feature_activation_helper"
        tags:
            - { name: form.type }
    
    rk_helper_module.form.type.infofinder:
        class: RK\HelperModule\Form\Type\Finder\InfoFinderType
        arguments:
            - "@translator.default"
            - "@rk_helper_module.feature_activation_helper"
        tags:
            - { name: form.type }
    
    rk_helper_module.form.type.appsettings:
        class: RK\HelperModule\Form\AppSettingsType
        arguments:
            - "@translator.default"
            - "@zikula_extensions_module.api.variable"
        tags:
            - { name: form.type }
