services:
    # Form field types
    
    pggo_team_module.form.type.field.datetime:
        class: Pggo\TeamModule\Form\Type\Field\DateTimeType
        tags:
            - { name: form.type }
    
    pggo_team_module.form.type.field.upload:
        class: Pggo\TeamModule\Form\Type\Field\UploadType
        arguments:
            - "@translator.default"
            - "@request_stack"
            - "@pggo_team_module.image_helper"
            - "@pggo_team_module.upload_helper"
        tags:
            - { name: form.type }
    
    pggo_team_module.form.type.field.user:
        class: Pggo\TeamModule\Form\Type\Field\UserType
        arguments:
            - "@zikula_users_module.user_repository"
        tags:
            - { name: form.type }
