services:
    # Form types
    
    pggo_team_module.form.type.personquicknav:
        class: Pggo\TeamModule\Form\Type\QuickNavigation\PersonQuickNavType
        arguments:
            - "@translator.default"
            - "@pggo_team_module.listentries_helper"
            - "@pggo_team_module.feature_activation_helper"
        tags:
            - { name: form.type }
    
    pggo_team_module.form.handler.person:
        class: Pggo\TeamModule\Form\Handler\Person\EditHandler
        arguments:
            - "@kernel"
            - "@translator.default"
            - "@form.factory"
            - "@request_stack"
            - "@router"
            - "@logger"
            - "@zikula_permissions_module.api.permission"
            - "@zikula_users_module.current_user"
            - "@pggo_team_module.entity_factory"
            - "@pggo_team_module.controller_helper"
            - "@pggo_team_module.model_helper"
            - "@pggo_team_module.selection_helper"
            - "@pggo_team_module.workflow_helper"
            - "@pggo_team_module.hook_helper"
            - "@pggo_team_module.feature_activation_helper"
        calls:
            - [setLockingApi, ["@?zikula_pagelock_module.api.locking"]]
        tags:
            - { name: form.type }
    
    pggo_team_module.form.type.person:
        class: Pggo\TeamModule\Form\Type\PersonType
        arguments:
            - "@translator.default"
            - "@pggo_team_module.entity_factory"
            - "@pggo_team_module.listentries_helper"
            - "@pggo_team_module.feature_activation_helper"
        tags:
            - { name: form.type }
    
    pggo_team_module.form.type.deleteentity:
        class: Pggo\TeamModule\Form\DeleteEntityType
        arguments:
            - "@translator.default"
        tags:
            - { name: form.type }
    
    pggo_team_module.form.type.block.itemlist:
        class: Pggo\TeamModule\Block\Form\Type\ItemListBlockType
        arguments:
            - "@translator.default"
        tags:
            - { name: form.type }
    
    pggo_team_module.form.type.appsettings:
        class: Pggo\TeamModule\Form\AppSettingsType
        arguments:
            - "@translator.default"
            - "@zikula_extensions_module.api.variable"
        tags:
            - { name: form.type }
