services:
    # Twig extension
    pggo_team_module.twig_extension:
        class: Pggo\TeamModule\Twig\TwigExtension
        arguments:
            - "@translator.default"
            - "@zikula_extensions_module.api.variable"
            - "@pggo_team_module.workflow_helper"
            - "@pggo_team_module.listentries_helper"
        public: false
        tags:
            - { name: twig.extension }
