<?php
/**
 * NewsDates.
 *
 * @copyright Ralf Koester (Pggo)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <webmaster@pggo.de>.
 * @link http://pggo.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace Pggo\NewsDatesModule\Helper;

use Pggo\NewsDatesModule\Helper\Base\AbstractSelectionHelper;

/**
 * Selection helper implementation class.
 */
class SelectionHelper extends AbstractSelectionHelper
{
    // feel free to extend the selection helper here
}
