<?php
/**
 * NewsDates.
 *
 * @copyright Ralf Koester (Pggo)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <webmaster@pggo.de>.
 * @link http://pggo.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace Pggo\NewsDatesModule\Form\Type;

use Pggo\NewsDatesModule\Form\Type\Base\AbstractArticleType;

/**
 * Article editing form type implementation class.
 */
class ArticleType extends AbstractArticleType
{
    // feel free to extend the article editing form type class here
}
