<?php
/**
 * NewsDates.
 *
 * @copyright Ralf Koester (Pggo)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <webmaster@pggo.de>.
 * @link http://pggo.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace Pggo\NewsDatesModule\Block;

use Pggo\NewsDatesModule\Block\Base\AbstractModerationBlock;

/**
 * Moderation block implementation class.
 */
class ModerationBlock extends AbstractModerationBlock
{
    // feel free to extend the moderation block here
}
