modules/News/templates/user/index.tpl: config/modules/News/templates/user/index.tpl
modules/News/templates/user/view.tpl: config/modules/News/templates/user/view.tpl
modules/News/templates/user/menu.tpl: config/modules/News/templates/user/menu.tpl
modules/News/templates/user/article.tpl: config/modules/News/templates/user/article.tpl
modules/News/templates/user/articlecontent.tpl: config/modules/News/templates/user/articlecontent.tpl
modules/News/templates/block/storiesext/row2.tpl: config/modules/News/templates/block/storiesext/row2.tpl
modules/News/templates/block/storiesext/main2.tpl: config/modules/News/templates/block/storiesext/main2.tpl
modules/News/templates/block/storiesext/row.tpl: config/modules/News/templates/block/storiesext/row.tpl