<?php
/**
 * Team.
 *
 * @copyright Ralf Koester (Pggo)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://pggo.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace Pggo\TeamModule\Form\Type\Field;

use Pggo\TeamModule\Form\Type\Field\Base\AbstractDateTimeType;

/**
 * Datetime field type implementation class.
 */
class DateTimeType extends AbstractDateTimeType
{
    // feel free to add your customisation here
}
