<?php
/**
 * MediaAttach.
 *
 * @copyright Ralf Koester (Pggo)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://pggo.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace Pggo\MediaAttachModule\Form\Handler\File;

use Pggo\MediaAttachModule\Form\Handler\File\Base\AbstractEditHandler;

/**
 * This handler class handles the page events of the Form called by the pggoMediaAttachModule_file_edit() function.
 * It aims on the file object type.
 */
class EditHandler extends AbstractEditHandler
{
    // feel free to extend the base handler class here
}
