<?php
/**
 * Instititutionen.
 *
 * @copyright Ralf Koester (Pggo)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace Pggo\InstititutionenModule\DependencyInjection;

use Pggo\InstititutionenModule\DependencyInjection\Base\AbstractPggoInstititutionenExtension;

/**
 * Implementation class for service definition loader using the DependencyInjection extension.
 */
class PggoInstititutionenExtension extends AbstractPggoInstititutionenExtension
{
    // custom enhancements can go here
}
