<?php
/**
 * DownLoad.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://oldtimer-ig-osnabrueck.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\DownLoadModule\Form\Type\Field;

use RK\DownLoadModule\Form\Type\Field\Base\AbstractDateTimeType;

/**
 * Datetime field type implementation class.
 */
class DateTimeType extends AbstractDateTimeType
{
    // feel free to add your customisation here
}
