<?php
/**
 * NewsDates.
 *
 * @copyright Ralf Koester (Pggo)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <webmaster@pggo.de>.
 * @link http://pggo.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace Pggo\NewsDatesModule\TaggedObjectMeta;

use Pggo\NewsDatesModule\TaggedObjectMeta\Base\AbstractPggoNewsDatesModule;

/**
 * This class provides object meta data for the Tag module.
 */
class PggoNewsDatesModule extends AbstractPggoNewsDatesModule
{
    // feel free to extend the tag support here
}
