<?php
/**
 * Team.
 *
 * @copyright Ralf Koester (Pggo)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://pggo.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace Pggo\TeamModule\Event\Base;

use Symfony\Component\EventDispatcher\Event;
use Pggo\TeamModule\Entity\PersonEntity;

/**
 * Event base class for filtering person processing.
 */
class AbstractFilterPersonEvent extends Event
{
    /**
     * @var PersonEntity Reference to treated entity instance.
     */
    protected $person;

    public function __construct(PersonEntity $person)
    {
        $this->person = $person;
    }

    public function getPerson()
    {
        return $this->person;
    }
}
