<?php
/**
 * Instititutionen.
 *
 * @copyright Ralf Koester (Pggo)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace Pggo\InstititutionenModule\Event\Base;

use Symfony\Component\EventDispatcher\Event;
use Pggo\InstititutionenModule\Entity\ImageEntity;

/**
 * Event base class for filtering image processing.
 */
class AbstractFilterImageEvent extends Event
{
    /**
     * @var ImageEntity Reference to treated entity instance.
     */
    protected $image;

    public function __construct(ImageEntity $image)
    {
        $this->image = $image;
    }

    public function getImage()
    {
        return $this->image;
    }
}
