<?php
/**
 * Instititutionen.
 *
 * @copyright Ralf Koester (Pggo)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace Pggo\InstititutionenModule\Form\Type\QuickNavigation;

use Pggo\InstititutionenModule\Form\Type\QuickNavigation\Base\AbstractInstitutionQuickNavType;

/**
 * Institution quick navigation form type implementation class.
 */
class InstitutionQuickNavType extends AbstractInstitutionQuickNavType
{
    // feel free to extend the base form type class here
}
