<?php
/**
 * NewsDates.
 *
 * @copyright Ralf Koester (Pggo)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <webmaster@pggo.de>.
 * @link http://pggo.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace Pggo\NewsDatesModule\Entity;

use Pggo\NewsDatesModule\Entity\Base\AbstractArticleCategoryEntity as BaseEntity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Entity extension domain class storing article categories.
 *
 * This is the concrete category class for article entities.
 * @ORM\Entity(repositoryClass="\Pggo\NewsDatesModule\Entity\Repository\ArticleCategoryRepository")
 * @ORM\Table(name="pggo_newsdate_article_category",
 *     uniqueConstraints={
 *         @ORM\UniqueConstraint(name="cat_unq", columns={"registryId", "categoryId", "entityId"})
 *     }
 * )
 */
class ArticleCategoryEntity extends BaseEntity
{
    // feel free to add your own methods here
}
