<?php
/**
 * NewsDates.
 *
 * @copyright Ralf Koester (Pggo)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <webmaster@pggo.de>.
 * @link http://pggo.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace Pggo\NewsDatesModule\Entity;

use Pggo\NewsDatesModule\Entity\Base\AbstractPictureEntity as BaseEntity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Validator\Constraints as Assert;
use Pggo\NewsDatesModule\Traits\EntityWorkflowTrait;

/**
 * Entity class that defines the entity structure and behaviours.
 *
 * This is the concrete entity class for picture entities.
 * @ORM\Entity(repositoryClass="Pggo\NewsDatesModule\Entity\Repository\PictureRepository")
 * @ORM\Table(name="pggo_newsdate_picture",
 *     indexes={
 *         @ORM\Index(name="workflowstateindex", columns={"workflowState"})
 *     }
 * )
 */
class PictureEntity extends BaseEntity
{
    // feel free to add your own methods here
}
