services:
    # Form types
    
    pggo_instititutionen_module.form.type.picturequicknav:
        class: Pggo\InstititutionenModule\Form\Type\QuickNavigation\PictureQuickNavType
        arguments:
            - "@translator.default"
            - "@request_stack"
            - "@pggo_instititutionen_module.listentries_helper"
            - "@pggo_instititutionen_module.feature_activation_helper"
        tags:
            - { name: form.type }
    
    pggo_instititutionen_module.form.type.institutionquicknav:
        class: Pggo\InstititutionenModule\Form\Type\QuickNavigation\InstitutionQuickNavType
        arguments:
            - "@translator.default"
            - "@pggo_instititutionen_module.listentries_helper"
            - "@pggo_instititutionen_module.feature_activation_helper"
        tags:
            - { name: form.type }
    
    pggo_instititutionen_module.form.handler.picture:
        class: Pggo\InstititutionenModule\Form\Handler\Picture\EditHandler
        arguments:
            - "@kernel"
            - "@translator.default"
            - "@form.factory"
            - "@request_stack"
            - "@router"
            - "@logger"
            - "@zikula_permissions_module.api.permission"
            - "@zikula_users_module.current_user"
            - "@pggo_instititutionen_module.entity_factory"
            - "@pggo_instititutionen_module.controller_helper"
            - "@pggo_instititutionen_module.model_helper"
            - "@pggo_instititutionen_module.selection_helper"
            - "@pggo_instititutionen_module.workflow_helper"
            - "@pggo_instititutionen_module.hook_helper"
            - "@pggo_instititutionen_module.feature_activation_helper"
        calls:
            - [setLockingApi, ["@?zikula_pagelock_module.api.locking"]]
        tags:
            - { name: form.type }
    
    pggo_instititutionen_module.form.type.picture:
        class: Pggo\InstititutionenModule\Form\Type\PictureType
        arguments:
            - "@translator.default"
            - "@pggo_instititutionen_module.entity_factory"
            - "@pggo_instititutionen_module.listentries_helper"
            - "@pggo_instititutionen_module.feature_activation_helper"
        tags:
            - { name: form.type }
    
    pggo_instititutionen_module.form.handler.institution:
        class: Pggo\InstititutionenModule\Form\Handler\Institution\EditHandler
        arguments:
            - "@kernel"
            - "@translator.default"
            - "@form.factory"
            - "@request_stack"
            - "@router"
            - "@logger"
            - "@zikula_permissions_module.api.permission"
            - "@zikula_users_module.current_user"
            - "@pggo_instititutionen_module.entity_factory"
            - "@pggo_instititutionen_module.controller_helper"
            - "@pggo_instititutionen_module.model_helper"
            - "@pggo_instititutionen_module.selection_helper"
            - "@pggo_instititutionen_module.workflow_helper"
            - "@pggo_instititutionen_module.hook_helper"
            - "@pggo_instititutionen_module.feature_activation_helper"
        calls:
            - [setLockingApi, ["@?zikula_pagelock_module.api.locking"]]
        tags:
            - { name: form.type }
    
    pggo_instititutionen_module.form.type.institution:
        class: Pggo\InstititutionenModule\Form\Type\InstitutionType
        arguments:
            - "@translator.default"
            - "@pggo_instititutionen_module.entity_factory"
            - "@pggo_instititutionen_module.listentries_helper"
            - "@pggo_instititutionen_module.feature_activation_helper"
        tags:
            - { name: form.type }
    
    pggo_instititutionen_module.form.type.block.itemlist:
        class: Pggo\InstititutionenModule\Block\Form\Type\ItemListBlockType
        arguments:
            - "@translator.default"
        tags:
            - { name: form.type }
    
    pggo_instititutionen_module.form.type.picturefinder:
        class: Pggo\InstititutionenModule\Form\Type\Finder\PictureFinderType
        arguments:
            - "@translator.default"
            - "@pggo_instititutionen_module.feature_activation_helper"
        tags:
            - { name: form.type }
    
    pggo_instititutionen_module.form.type.institutionfinder:
        class: Pggo\InstititutionenModule\Form\Type\Finder\InstitutionFinderType
        arguments:
            - "@translator.default"
            - "@pggo_instititutionen_module.feature_activation_helper"
        tags:
            - { name: form.type }
    
    pggo_instititutionen_module.form.type.appsettings:
        class: Pggo\InstititutionenModule\Form\AppSettingsType
        arguments:
            - "@translator.default"
            - "@zikula_extensions_module.api.variable"
        tags:
            - { name: form.type }
