services:
    # Entity factory class
    rk_helper_module.entity_factory:
        class: RK\HelperModule\Entity\Factory\HelperFactory
        arguments:
            - "@doctrine.orm.default_entity_manager"
