<?php
/**
 * Instititutionen.
 *
 * @copyright Ralf Koester (Pggo)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace Pggo\InstititutionenModule\Form\DataTransformer;

use Pggo\InstititutionenModule\Form\DataTransformer\Base\AbstractUploadFileTransformer;

/**
 * Upload file transformer implementation class.
 *
 * This data transformer treats uploaded files.
 */
class UploadFileTransformer extends AbstractUploadFileTransformer
{
    // feel free to add your customisation here
}
