<?php
/**
 * MediaAttach.
 *
 * @copyright Ralf Koester (Pggo)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://pggo.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace Pggo\MediaAttachModule;

use Pggo\MediaAttachModule\Base\AbstractMediaAttachEvents;

/**
 * Events definition implementation class.
 */
class MediaAttachEvents extends AbstractMediaAttachEvents
{
    // feel free to extend the events definition here
}
