<?php
/**
 * DownLoad.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://oldtimer-ig-osnabrueck.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\DownLoadModule\Helper;

use RK\DownLoadModule\Helper\Base\AbstractArchiveHelper;

/**
 * Archive helper implementation class.
 */
class ArchiveHelper extends AbstractArchiveHelper
{
    // feel free to extend the archive helper here
}
