<?php
/**
 * Helper.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\HelperModule\Container\Base;

use Zikula\Bundle\HookBundle\AbstractHookContainer as ZikulaHookContainer;

use Zikula\Bundle\HookBundle\Bundle\SubscriberBundle;

/**
 * Base class for hook container methods.
 */
abstract class AbstractHookContainer extends ZikulaHookContainer
{
    /**
     * Define the hook bundles supported by this module.
     *
     * @return void
     */
    protected function setupHookBundles()
    {
        $bundle = new SubscriberBundle('RKHelperModule', 'subscriber.rkhelpermodule.ui_hooks.linkers', 'ui_hooks', $this->__('rkhelpermodule. Linkers Display Hooks'));
        
        // Display hook for view/display templates.
        $bundle->addEvent('display_view', 'rkhelpermodule.ui_hooks.linkers.display_view');
        // Display hook for create/edit forms.
        $bundle->addEvent('form_edit', 'rkhelpermodule.ui_hooks.linkers.form_edit');
        // Display hook for delete dialogues.
        $bundle->addEvent('form_delete', 'rkhelpermodule.ui_hooks.linkers.form_delete');
        // Validate input from an ui create/edit form.
        $bundle->addEvent('validate_edit', 'rkhelpermodule.ui_hooks.linkers.validate_edit');
        // Validate input from an ui delete form.
        $bundle->addEvent('validate_delete', 'rkhelpermodule.ui_hooks.linkers.validate_delete');
        // Perform the final update actions for a ui create/edit form.
        $bundle->addEvent('process_edit', 'rkhelpermodule.ui_hooks.linkers.process_edit');
        // Perform the final delete actions for a ui form.
        $bundle->addEvent('process_delete', 'rkhelpermodule.ui_hooks.linkers.process_delete');
        $this->registerHookSubscriberBundle($bundle);
        
        $bundle = new SubscriberBundle('RKHelperModule', 'subscriber.rkhelpermodule.filter_hooks.linkers', 'filter_hooks', $this->__('rkhelpermodule. Linkers Filter Hooks'));
        // A filter applied to the given area.
        $bundle->addEvent('filter', 'rkhelpermodule.filter_hooks.linkers.filter');
        $this->registerHookSubscriberBundle($bundle);
        
        $bundle = new SubscriberBundle('RKHelperModule', 'subscriber.rkhelpermodule.ui_hooks.carouselitems', 'ui_hooks', $this->__('rkhelpermodule. Carousel items Display Hooks'));
        
        // Display hook for view/display templates.
        $bundle->addEvent('display_view', 'rkhelpermodule.ui_hooks.carouselitems.display_view');
        // Display hook for create/edit forms.
        $bundle->addEvent('form_edit', 'rkhelpermodule.ui_hooks.carouselitems.form_edit');
        // Display hook for delete dialogues.
        $bundle->addEvent('form_delete', 'rkhelpermodule.ui_hooks.carouselitems.form_delete');
        // Validate input from an ui create/edit form.
        $bundle->addEvent('validate_edit', 'rkhelpermodule.ui_hooks.carouselitems.validate_edit');
        // Validate input from an ui delete form.
        $bundle->addEvent('validate_delete', 'rkhelpermodule.ui_hooks.carouselitems.validate_delete');
        // Perform the final update actions for a ui create/edit form.
        $bundle->addEvent('process_edit', 'rkhelpermodule.ui_hooks.carouselitems.process_edit');
        // Perform the final delete actions for a ui form.
        $bundle->addEvent('process_delete', 'rkhelpermodule.ui_hooks.carouselitems.process_delete');
        $this->registerHookSubscriberBundle($bundle);
        
        $bundle = new SubscriberBundle('RKHelperModule', 'subscriber.rkhelpermodule.filter_hooks.carouselitems', 'filter_hooks', $this->__('rkhelpermodule. Carousel items Filter Hooks'));
        // A filter applied to the given area.
        $bundle->addEvent('filter', 'rkhelpermodule.filter_hooks.carouselitems.filter');
        $this->registerHookSubscriberBundle($bundle);
        
        $bundle = new SubscriberBundle('RKHelperModule', 'subscriber.rkhelpermodule.ui_hooks.carousells', 'ui_hooks', $this->__('rkhelpermodule. Carousells Display Hooks'));
        
        // Display hook for view/display templates.
        $bundle->addEvent('display_view', 'rkhelpermodule.ui_hooks.carousells.display_view');
        // Display hook for create/edit forms.
        $bundle->addEvent('form_edit', 'rkhelpermodule.ui_hooks.carousells.form_edit');
        // Display hook for delete dialogues.
        $bundle->addEvent('form_delete', 'rkhelpermodule.ui_hooks.carousells.form_delete');
        // Validate input from an ui create/edit form.
        $bundle->addEvent('validate_edit', 'rkhelpermodule.ui_hooks.carousells.validate_edit');
        // Validate input from an ui delete form.
        $bundle->addEvent('validate_delete', 'rkhelpermodule.ui_hooks.carousells.validate_delete');
        // Perform the final update actions for a ui create/edit form.
        $bundle->addEvent('process_edit', 'rkhelpermodule.ui_hooks.carousells.process_edit');
        // Perform the final delete actions for a ui form.
        $bundle->addEvent('process_delete', 'rkhelpermodule.ui_hooks.carousells.process_delete');
        $this->registerHookSubscriberBundle($bundle);
        
        $bundle = new SubscriberBundle('RKHelperModule', 'subscriber.rkhelpermodule.filter_hooks.carousells', 'filter_hooks', $this->__('rkhelpermodule. Carousells Filter Hooks'));
        // A filter applied to the given area.
        $bundle->addEvent('filter', 'rkhelpermodule.filter_hooks.carousells.filter');
        $this->registerHookSubscriberBundle($bundle);
        
        $bundle = new SubscriberBundle('RKHelperModule', 'subscriber.rkhelpermodule.ui_hooks.images', 'ui_hooks', $this->__('rkhelpermodule. Images Display Hooks'));
        
        // Display hook for view/display templates.
        $bundle->addEvent('display_view', 'rkhelpermodule.ui_hooks.images.display_view');
        // Display hook for create/edit forms.
        $bundle->addEvent('form_edit', 'rkhelpermodule.ui_hooks.images.form_edit');
        // Display hook for delete dialogues.
        $bundle->addEvent('form_delete', 'rkhelpermodule.ui_hooks.images.form_delete');
        // Validate input from an ui create/edit form.
        $bundle->addEvent('validate_edit', 'rkhelpermodule.ui_hooks.images.validate_edit');
        // Validate input from an ui delete form.
        $bundle->addEvent('validate_delete', 'rkhelpermodule.ui_hooks.images.validate_delete');
        // Perform the final update actions for a ui create/edit form.
        $bundle->addEvent('process_edit', 'rkhelpermodule.ui_hooks.images.process_edit');
        // Perform the final delete actions for a ui form.
        $bundle->addEvent('process_delete', 'rkhelpermodule.ui_hooks.images.process_delete');
        $this->registerHookSubscriberBundle($bundle);
        
        $bundle = new SubscriberBundle('RKHelperModule', 'subscriber.rkhelpermodule.filter_hooks.images', 'filter_hooks', $this->__('rkhelpermodule. Images Filter Hooks'));
        // A filter applied to the given area.
        $bundle->addEvent('filter', 'rkhelpermodule.filter_hooks.images.filter');
        $this->registerHookSubscriberBundle($bundle);
        
        $bundle = new SubscriberBundle('RKHelperModule', 'subscriber.rkhelpermodule.ui_hooks.infos', 'ui_hooks', $this->__('rkhelpermodule. Infos Display Hooks'));
        
        // Display hook for view/display templates.
        $bundle->addEvent('display_view', 'rkhelpermodule.ui_hooks.infos.display_view');
        // Display hook for create/edit forms.
        $bundle->addEvent('form_edit', 'rkhelpermodule.ui_hooks.infos.form_edit');
        // Display hook for delete dialogues.
        $bundle->addEvent('form_delete', 'rkhelpermodule.ui_hooks.infos.form_delete');
        // Validate input from an ui create/edit form.
        $bundle->addEvent('validate_edit', 'rkhelpermodule.ui_hooks.infos.validate_edit');
        // Validate input from an ui delete form.
        $bundle->addEvent('validate_delete', 'rkhelpermodule.ui_hooks.infos.validate_delete');
        // Perform the final update actions for a ui create/edit form.
        $bundle->addEvent('process_edit', 'rkhelpermodule.ui_hooks.infos.process_edit');
        // Perform the final delete actions for a ui form.
        $bundle->addEvent('process_delete', 'rkhelpermodule.ui_hooks.infos.process_delete');
        $this->registerHookSubscriberBundle($bundle);
        
        $bundle = new SubscriberBundle('RKHelperModule', 'subscriber.rkhelpermodule.filter_hooks.infos', 'filter_hooks', $this->__('rkhelpermodule. Infos Filter Hooks'));
        // A filter applied to the given area.
        $bundle->addEvent('filter', 'rkhelpermodule.filter_hooks.infos.filter');
        $this->registerHookSubscriberBundle($bundle);
        
        
        
    }
}
