<?php
/**
 * Helper.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\HelperModule\Event\Base;

use Symfony\Component\EventDispatcher\Event;
use RK\HelperModule\Entity\CarouselItemEntity;

/**
 * Event base class for filtering carousel item processing.
 */
class AbstractFilterCarouselItemEvent extends Event
{
    /**
     * @var CarouselItemEntity Reference to treated entity instance.
     */
    protected $carouselItem;

    public function __construct(CarouselItemEntity $carouselItem)
    {
        $this->carouselItem = $carouselItem;
    }

    public function getCarouselItem()
    {
        return $this->carouselItem;
    }
}
