<?php
/**
 * Helper.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\HelperModule\Form\Type\QuickNavigation;

use RK\HelperModule\Form\Type\QuickNavigation\Base\AbstractImageQuickNavType;

/**
 * Image quick navigation form type implementation class.
 */
class ImageQuickNavType extends AbstractImageQuickNavType
{
    // feel free to extend the base form type class here
}
