<?php
/**
 * Helper.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\HelperModule\Form\Handler\Carousel;

use RK\HelperModule\Form\Handler\Carousel\Base\AbstractEditHandler;

/**
 * This handler class handles the page events of the Form called by the rKHelperModule_carousel_edit() function.
 * It aims on the carousel object type.
 */
class EditHandler extends AbstractEditHandler
{
    // feel free to extend the base handler class here
}
