<?php
/**
 * Helper.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\HelperModule\Form\Type;

use RK\HelperModule\Form\Type\Base\AbstractCarouselItemType;

/**
 * Carousel item editing form type implementation class.
 */
class CarouselItemType extends AbstractCarouselItemType
{
    // feel free to extend the carousel item editing form type class here
}
