<?php
/**
 * DownLoad.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://oldtimer-ig-osnabrueck.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\DownLoadModule\Form\Type\QuickNavigation;

use RK\DownLoadModule\Form\Type\QuickNavigation\Base\AbstractFileQuickNavType;

/**
 * File quick navigation form type implementation class.
 */
class FileQuickNavType extends AbstractFileQuickNavType
{
    // feel free to extend the base form type class here
}
