<?php
/**
 * Helper.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://oldtimer-ig-osnabrueck.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

namespace RK\HelperModule;

use RK\HelperModule\Base\AbstractHelperModuleInstaller;

/**
 * Installer implementation class.
 */
class HelperModuleInstaller extends AbstractHelperModuleInstaller
{
    // feel free to extend the installer here
	public function install()

{

    $result = parent::install();

 

    if (true === $result) {

        // eigene Werte setzen
		$this->setVar('enableShrinkingForLinkerLinkerImage', true);
        $this->setVar('shrinkWidthLinkerLinkerImage', 800);
        $this->setVar('shrinkHeightLinkerLinkerImage', 600);
        $this->setVar('enableShrinkingForCarouselImageItemImage', true);
        $this->setVar('shrinkWidthCarouselImageItemImage', 1800);
        $this->setVar('shrinkHeightCarouselImageItemImage', 600);
        $this->setVar('enableShrinkingForWebsiteImageMyImage', true);
        $this->setVar('shrinkWidthWebsiteImageMyImage', 800);
        $this->setVar('shrinkHeightWebsiteImageMyImage', 600);

    }

 

    return $result;

}

 
}
