<?php
/**
 * NewsDates.
 *
 * @copyright Ralf Koester (Pggo)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <webmaster@pggo.de>.
 * @link http://pggo.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace Pggo\NewsDatesModule\ContentType;

use Pggo\NewsDatesModule\ContentType\Base\AbstractItem;

/**
 * Generic single item display content plugin implementation class.
 */
class Item extends AbstractItem
{
    // feel free to extend the content type here
}
