<?php
/**
 * Team.
 *
 * @copyright Ralf Koester (Pggo)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://pggo.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace Pggo\TeamModule\Form\Type;

use Pggo\TeamModule\Form\Type\Base\AbstractPersonType;

/**
 * Person editing form type implementation class.
 */
class PersonType extends AbstractPersonType
{
    // feel free to extend the person editing form type class here
}
