<?php
/**
 * DownLoad.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://oldtimer-ig-osnabrueck.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\DownLoadModule\Entity\Base;

use Doctrine\ORM\Mapping as ORM;
use Zikula\CategoriesModule\Entity\AbstractCategoryAssignment;

/**
 * Entity extension domain class storing file categories.
 *
 * This is the base category class for file entities.
 */
abstract class AbstractFileCategoryEntity extends AbstractCategoryAssignment
{
    /**
     * @ORM\ManyToOne(targetEntity="\RK\DownLoadModule\Entity\FileEntity", inversedBy="categories")
     * @ORM\JoinColumn(name="entityId", referencedColumnName="id")
     * @var \RK\DownLoadModule\Entity\FileEntity
     */
    protected $entity;
    
    /**
     * Get reference to owning entity.
     *
     * @return \RK\DownLoadModule\Entity\FileEntity
     */
    public function getEntity()
    {
        return $this->entity;
    }
    
    /**
     * Set reference to owning entity.
     *
     * @param \RK\DownLoadModule\Entity\FileEntity $entity
     */
    public function setEntity(/*\RK\DownLoadModule\Entity\FileEntity */$entity)
    {
        $this->entity = $entity;
    }
}
