services:
    # Form types
    
    pggo_newsdates_module.form.type.articlequicknav:
        class: Pggo\NewsDatesModule\Form\Type\QuickNavigation\ArticleQuickNavType
        arguments:
            - "@translator.default"
            - "@pggo_newsdates_module.listentries_helper"
            - "@pggo_newsdates_module.feature_activation_helper"
        tags:
            - { name: form.type }
    
    pggo_newsdates_module.form.type.picturequicknav:
        class: Pggo\NewsDatesModule\Form\Type\QuickNavigation\PictureQuickNavType
        arguments:
            - "@translator.default"
            - "@request_stack"
            - "@pggo_newsdates_module.listentries_helper"
            - "@pggo_newsdates_module.feature_activation_helper"
        tags:
            - { name: form.type }
    
    pggo_newsdates_module.form.type.eventquicknav:
        class: Pggo\NewsDatesModule\Form\Type\QuickNavigation\EventQuickNavType
        arguments:
            - "@translator.default"
            - "@request_stack"
            - "@pggo_newsdates_module.listentries_helper"
            - "@pggo_newsdates_module.feature_activation_helper"
        tags:
            - { name: form.type }
    
    pggo_newsdates_module.form.handler.article:
        class: Pggo\NewsDatesModule\Form\Handler\Article\EditHandler
        arguments:
            - "@kernel"
            - "@translator.default"
            - "@form.factory"
            - "@request_stack"
            - "@router"
            - "@logger"
            - "@zikula_permissions_module.api.permission"
            - "@zikula_extensions_module.api.variable"
            - "@zikula_users_module.current_user"
            - "@zikula_groups_module.group_application_repository"
            - "@pggo_newsdates_module.entity_factory"
            - "@pggo_newsdates_module.controller_helper"
            - "@pggo_newsdates_module.model_helper"
            - "@pggo_newsdates_module.selection_helper"
            - "@pggo_newsdates_module.workflow_helper"
            - "@pggo_newsdates_module.hook_helper"
            - "@pggo_newsdates_module.feature_activation_helper"
        calls:
            - [setLockingApi, ["@?zikula_pagelock_module.api.locking"]]
        tags:
            - { name: form.type }
    
    pggo_newsdates_module.form.type.article:
        class: Pggo\NewsDatesModule\Form\Type\ArticleType
        arguments:
            - "@translator.default"
            - "@pggo_newsdates_module.entity_factory"
            - "@pggo_newsdates_module.listentries_helper"
            - "@pggo_newsdates_module.feature_activation_helper"
        tags:
            - { name: form.type }
    
    pggo_newsdates_module.form.handler.picture:
        class: Pggo\NewsDatesModule\Form\Handler\Picture\EditHandler
        arguments:
            - "@kernel"
            - "@translator.default"
            - "@form.factory"
            - "@request_stack"
            - "@router"
            - "@logger"
            - "@zikula_permissions_module.api.permission"
            - "@zikula_extensions_module.api.variable"
            - "@zikula_users_module.current_user"
            - "@zikula_groups_module.group_application_repository"
            - "@pggo_newsdates_module.entity_factory"
            - "@pggo_newsdates_module.controller_helper"
            - "@pggo_newsdates_module.model_helper"
            - "@pggo_newsdates_module.selection_helper"
            - "@pggo_newsdates_module.workflow_helper"
            - "@pggo_newsdates_module.hook_helper"
            - "@pggo_newsdates_module.feature_activation_helper"
        calls:
            - [setLockingApi, ["@?zikula_pagelock_module.api.locking"]]
        tags:
            - { name: form.type }
    
    pggo_newsdates_module.form.type.picture:
        class: Pggo\NewsDatesModule\Form\Type\PictureType
        arguments:
            - "@translator.default"
            - "@pggo_newsdates_module.entity_factory"
            - "@pggo_newsdates_module.listentries_helper"
            - "@pggo_newsdates_module.feature_activation_helper"
        tags:
            - { name: form.type }
    
    pggo_newsdates_module.form.handler.event:
        class: Pggo\NewsDatesModule\Form\Handler\Event\EditHandler
        arguments:
            - "@kernel"
            - "@translator.default"
            - "@form.factory"
            - "@request_stack"
            - "@router"
            - "@logger"
            - "@zikula_permissions_module.api.permission"
            - "@zikula_extensions_module.api.variable"
            - "@zikula_users_module.current_user"
            - "@zikula_groups_module.group_application_repository"
            - "@pggo_newsdates_module.entity_factory"
            - "@pggo_newsdates_module.controller_helper"
            - "@pggo_newsdates_module.model_helper"
            - "@pggo_newsdates_module.selection_helper"
            - "@pggo_newsdates_module.workflow_helper"
            - "@pggo_newsdates_module.hook_helper"
            - "@pggo_newsdates_module.feature_activation_helper"
        calls:
            - [setLockingApi, ["@?zikula_pagelock_module.api.locking"]]
        tags:
            - { name: form.type }
    
    pggo_newsdates_module.form.type.event:
        class: Pggo\NewsDatesModule\Form\Type\EventType
        arguments:
            - "@translator.default"
            - "@pggo_newsdates_module.entity_factory"
            - "@pggo_newsdates_module.listentries_helper"
            - "@pggo_newsdates_module.feature_activation_helper"
        tags:
            - { name: form.type }
    
    pggo_newsdates_module.form.type.deleteentity:
        class: Pggo\NewsDatesModule\Form\DeleteEntityType
        arguments:
            - "@translator.default"
        tags:
            - { name: form.type }
    
    pggo_newsdates_module.form.type.block.itemlist:
        class: Pggo\NewsDatesModule\Block\Form\Type\ItemListBlockType
        arguments:
            - "@translator.default"
        tags:
            - { name: form.type }
    
    pggo_newsdates_module.form.type.articlefinder:
        class: Pggo\NewsDatesModule\Form\Type\Finder\ArticleFinderType
        arguments:
            - "@translator.default"
            - "@pggo_newsdates_module.feature_activation_helper"
        tags:
            - { name: form.type }
    
    pggo_newsdates_module.form.type.picturefinder:
        class: Pggo\NewsDatesModule\Form\Type\Finder\PictureFinderType
        arguments:
            - "@translator.default"
            - "@pggo_newsdates_module.feature_activation_helper"
        tags:
            - { name: form.type }
    
    pggo_newsdates_module.form.type.eventfinder:
        class: Pggo\NewsDatesModule\Form\Type\Finder\EventFinderType
        arguments:
            - "@translator.default"
            - "@pggo_newsdates_module.feature_activation_helper"
        tags:
            - { name: form.type }
    
    pggo_newsdates_module.form.type.appsettings:
        class: Pggo\NewsDatesModule\Form\AppSettingsType
        arguments:
            - "@translator.default"
            - "@zikula_extensions_module.api.variable"
            - "@zikula_groups_module.group_repository"
        tags:
            - { name: form.type }
