<?php
/**
 * Helper.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\HelperModule\Event\Base;

use Symfony\Component\EventDispatcher\Event;
use RK\HelperModule\Entity\InfoEntity;

/**
 * Event base class for filtering info processing.
 */
class AbstractFilterInfoEvent extends Event
{
    /**
     * @var InfoEntity Reference to treated entity instance.
     */
    protected $info;

    public function __construct(InfoEntity $info)
    {
        $this->info = $info;
    }

    public function getInfo()
    {
        return $this->info;
    }
}
