<?php
/**
 * NewsDates.
 *
 * @copyright Ralf Koester (Pggo)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <webmaster@pggo.de>.
 * @link http://pggo.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace Pggo\NewsDatesModule\Helper\Base;

use Psr\Log\LoggerInterface;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Zikula\Common\Translator\TranslatorInterface;
use Zikula\PermissionsModule\Api\PermissionApi;
use Pggo\NewsDatesModule\Entity\Factory\NewsDatesFactory;
use Pggo\NewsDatesModule\Helper\HookHelper;
use Pggo\NewsDatesModule\Helper\WorkflowHelper;

/**
 * Archive helper base class.
 */
abstract class AbstractArchiveHelper
{
    /**
     * @var TranslatorInterface
     */
    protected $translator;

    /**
     * @var SessionInterface
     */
    protected $session;

    /**
     * @var LoggerInterface
     */
    protected $logger;

    /**
     * @var PermissionApi
     */
    protected $permissionApi;

    /**
     * @var NewsDatesFactory
     */
    protected $entityFactory;

    /**
     * @var WorkflowHelper
     */
    protected $workflowHelper;

    /**
     * @var HookHelper
     */
    protected $hookHelper;

    /**
     * ArchiveHelper constructor.
     *
     * @param TranslatorInterface $translator     Translator service instance
     * @param SessionInterface    $session        Session service instance
     * @param LoggerInterface     $logger         Logger service instance
     * @param PermissionApi       $permissionApi  PermissionApi service instance
     * @param NewsDatesFactory $entityFactory NewsDatesFactory service instance
     * @param WorkflowHelper      $workflowHelper WorkflowHelper service instance
     * @param HookHelper          $hookHelper     HookHelper service instance
     */
    public function __construct(
        TranslatorInterface $translator,
        SessionInterface $session,
        LoggerInterface $logger,
        PermissionApi $permissionApi,
        NewsDatesFactory $entityFactory,
        WorkflowHelper $workflowHelper,
        HookHelper $hookHelper)
    {
        $this->translator = $translator;
        $this->session = $session;
        $this->logger = $logger;
        $this->permissionApi = $permissionApi;
        $this->entityFactory = $entityFactory;
        $this->workflowHelper = $workflowHelper;
        $this->hookHelper = $hookHelper;
    }

    /**
     * Moves obsolete data into the archive.
     */
    public function archiveObjects()
    {
        $randProbability = mt_rand(1, 1000);
    
        if ($randProbability < 750) {
            return;
        }
    
        $this->session->set('PggoNewsDatesModuleAutomaticArchiving', true);
    
        // perform update for articles becoming archived
        $logArgs = ['app' => 'PggoNewsDatesModule', 'entity' => 'article'];
        $this->logger->notice('{app}: Automatic archiving for the {entity} entity started.', $logArgs);
        $repository = $this->entityFactory->getRepository('article');
        $repository->archiveObjects($this->permissionApi, $this->session, $this->translator, $this->workflowHelper, $this->hookHelper);
        $this->logger->notice('{app}: Automatic archiving for the {entity} entity completed.', $logArgs);
    
        $this->session->del('PggoNewsDatesModuleAutomaticArchiving');
    }
}
