<?php
/**
 * Team.
 *
 * @copyright Ralf Koester (Pggo)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://pggo.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace Pggo\TeamModule\Helper;

use Pggo\TeamModule\Helper\Base\AbstractSearchHelper;

/**
 * Search helper implementation class.
 */
class SearchHelper extends AbstractSearchHelper
{
    // feel free to extend the search helper here
}
