<?php
/**
 * Helper.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\HelperModule\Event;

use RK\HelperModule\Event\Base\AbstractFilterCarouselItemEvent;

/**
 * Event implementation class for filtering carousel item processing.
 */
class FilterCarouselItemEvent extends AbstractFilterCarouselItemEvent
{
    // feel free to extend the event class here
}
