<?php
/**
 * MediaAttach.
 *
 * @copyright Ralf Koester (Pggo)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://pggo.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace Pggo\MediaAttachModule\Form\Type;

use Pggo\MediaAttachModule\Form\Type\Base\AbstractFileType;

/**
 * File editing form type implementation class.
 */
class FileType extends AbstractFileType
{
    // feel free to extend the file editing form type class here
}
