<?php
/**
 * Team.
 *
 * @copyright Ralf Koester (Pggo)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://pggo.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace Pggo\TeamModule;

use Pggo\TeamModule\Base\AbstractPggoTeamModule;

/**
 * Module implementation class.
 */
class PggoTeamModule extends AbstractPggoTeamModule
{
    // custom enhancements can go here
}
