<?php
/**
 * Team.
 *
 * @copyright Ralf Koester (Pggo)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://pggo.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace Pggo\TeamModule;

use Pggo\TeamModule\Base\AbstractTeamModuleInstaller;

/**
 * Installer implementation class.
 */
class TeamModuleInstaller extends AbstractTeamModuleInstaller
{
    // feel free to extend the installer here
}
