## YAML Override template
## original/file.tpl: override/file.tpl
---
system/BlocksModule/Resources/views/Block/Extmenu/topnav.tpl: themes/Pggo/X2017Theme/Resources/views/modules/ZikulaBlocksModule/Block/Extmenu/topnav.tpl
