<?php
/**
 * NewsDates.
 *
 * @copyright Ralf Koester (Pggo)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <webmaster@pggo.de>.
 * @link http://pggo.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace Pggo\NewsDatesModule;

use Pggo\NewsDatesModule\Base\AbstractNewsDatesEvents;

/**
 * Events definition implementation class.
 */
class NewsDatesEvents extends AbstractNewsDatesEvents
{
    // feel free to extend the events definition here
}
