<?php
/**
 * Instititutionen.
 *
 * @copyright Ralf Koester (Pggo)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace Pggo\InstititutionenModule\Entity\Repository;

use Pggo\InstititutionenModule\Entity\Repository\Base\AbstractInstitutionRepository;

/**
 * Repository class used to implement own convenience methods for performing certain DQL queries.
 *
 * This is the concrete repository class for institution entities.
 */
class InstitutionRepository extends AbstractInstitutionRepository
{
    // feel free to add your own methods here, like for example reusable DQL queries
}
