<?php
/**
 * NewsDates.
 *
 * @copyright Ralf Koester (Pggo)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <webmaster@pggo.de>.
 * @link http://pggo.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace Pggo\NewsDatesModule\Block\Form\Type;

use Pggo\NewsDatesModule\Block\Form\Type\Base\AbstractItemListBlockType;

/**
 * List block form type implementation class.
 */
class ItemListBlockType extends AbstractItemListBlockType
{
    // feel free to extend the list block form type class here
}
