<?php
/**
 * Instititutionen.
 *
 * @copyright Ralf Koester (Pggo)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace Pggo\InstititutionenModule\Event;

use Pggo\InstititutionenModule\Event\Base\AbstractFilterInstitutionEvent;

/**
 * Event implementation class for filtering institution processing.
 */
class FilterInstitutionEvent extends AbstractFilterInstitutionEvent
{
    // feel free to extend the event class here
}
